### ISSUE TITLE
Access to the thesis and the dataset

### ISSUE THREAD

**Issue by tianfrank** [zhengwuma/LexicalComplexity_RatedQuality#1]
Dear Zhengwu, it seems that we have no access to the thesis, and the hyperlink to the dataset no longer works.

**Comment by zhengwuma** [comment]
Hi, I have updated the dataset link for viewing. If you need access to it, please email me, and I will send you the entire folder. (zhengwumaa@gmail, or zhengwu.ma@my.cityu.edu.hk)
